export {
  EVIL_SQUIRREL_BUILDER_CODE as BASE_BUILDER_CODE,
  EVIL_SQUIRREL_BUILDER_CODE_DATA_SUFFIX as BASE_BUILDER_CODE_DATA_SUFFIX,
  EVIL_SQUIRREL_CHECKIN_INTERVAL_SECONDS as CHECK_IN_INTERVAL_SECONDS,
  EVIL_SQUIRREL_CHECKIN_PRICE_ETH as CHECK_IN_PRICE_ETH,
  EVIL_SQUIRREL_CONTRACT_ADDRESS as CHECK_IN_CONTRACT_ADDRESS,
  evilSquirrelOnchainAbi as checkInAbi,
  getEvilSquirrelContractAddress,
  withEvilSquirrelBuilderCodeDataSuffix,
} from "@/lib/contracts/evilSquirrelOnchain";
